trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: git
      name: roboshop/roboshop-shared-templates
      ref: refs/heads/main

extends:
  template: templates/nodejs-azure-pipeline.yml@templates
  parameters:
    project: 'roboshop'
    component: 'user'
    deploy: false